# Generated by Django 6.0.7 on 2026-07-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('ADICIONAL', 'Adicional')], default='SERVICO', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracao_min', models.PositiveIntegerField(blank=True, null=True)),
                ('ocupa_agenda', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
