# Generated by Django 6.0.7 on 2026-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='itens',
            field=models.ManyToManyField(blank=True, to='core.itemcatalogo'),
        ),
    ]
