# Generated by Django 6.0.7 on 2026-07-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendamento_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CASAMENTO', 'Casamento'), ('ANIVERSARIO', 'Aniversário'), ('FORMATURA', 'Formatura'), ('ENSAIO', 'Ensaio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data_evento', models.DateField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('valor_sinal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'ordering': ['data_evento'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento'),
        ),
    ]
