# Generated by Django 6.0.7 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evento_agendamento_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor_sinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
