# Generated by Django 6.0.7 on 2026-08-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.evento'),
        ),
    ]
