# Generated by Django 6.0.7 on 2026-08-09 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='core.evento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.itemcatalogo')),
            ],
        ),
    ]
