# Generated by Django 6.0.7 on 2026-08-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_evento_token_itemorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='local',
            field=models.CharField(choices=[('ESTUDIO', 'Estúdio'), ('DOMICILIO', 'Domicílio')], default='ESTUDIO', max_length=20),
        ),
    ]
