# Generated by Django 6.0.7 on 2026-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agendamento_endereco_agendamento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.CharField(blank=True, help_text='Separe por vírgula: Noiva, VIP', max_length=100),
        ),
    ]
